export const value = [
  {
    title: "Project Topic Assessment",
    desc: "Initial topic assessment document of the proposed research was submitted for evaluation. The submitted document included a brief overview on key aspects of the proposed research along with the research problem, research objectives, overall solution as well as member task breakdown.",
    marks: "No marks allocated",
    date: "January 2023",
    type: "doc",
  },
  {
    title: "Project Charter Submission",
    desc: "Once the topic was finalized, the project charter document was submitted for evaluation. This document also included a brief overview on key aspects of the proposed research along with the research problem, research objectives, overall solution as well as member task breakdown of the proposed research.",
    marks: "No marks allocated",
    date: "January 20 2023",
    type: "doc",
  },
  {
    title: "Project Proposal Presentation",
    desc: "Presented to a panel of judges in order to provide an overview of the proposed research.",
    marks: "Marks Allocation - 6%",
    date: "March 27 2023",
    type: "viva",
  },
  {
    title: "Project Proposal Report",
    desc: "The submission of a report which provides an in-depth analysis pertaining to key aspects of the proposed research along with the research problem, objectives, as well as the overall proposed solution. ",
    marks: "Marks Allocation - 6%",
    date: "May 5, 2023",
    type: "doc",
  },
  {
    title: "Status Document 1",
    desc: "The submission of a document that provides an overview of key tasks conducted by members during the implementation phase of the research.",
    marks: "Marks Allocation - 1%",
    date: "May 22, 2023",
    type: "doc",
  },
  {
    title: "Progress Presentation 1",
    desc: "Evaluation of 50% completion of the proposed solution by a panel of judges.",
    marks: "Marks Allocation - 15%",
    date: "May 22, 2023",
    type: "viva",
  },
  {
    title: "Research Paper draft submission",
    desc: "Draft submission of the research paper submitted to the supervisor for evaluation.",
    marks: "Marks Allocation - 10%",
    date: "June 20, 2023",
    type: "doc",
  },
  {
    title: "Status Document 2",
    desc: "The submission of a document that provides an overview of key tasks conducted by members during the implementation phase of the research.",
    marks: "Marks Allocation - 1%",
    date: "September 4, 2023",
    type: "doc",
  },
  {
    title: "Progress Presentation 2",
    desc: "Evaluation of 90% completion of the proposed solution by a panel of judges.",
    marks: "Marks Allocation - 18%",
    date: "September 4, 2023",
    type: "viva",
  },
  {
    title: "Final Thesis Submission",
    desc: "Submission of the group and individual thesis documents for evaluation.",
    marks: "Marks Allocation - 19%",
    date: "September 10, 2023",
    type: "doc",
  },
  {
    title: "Log Book and Status Document 2",
    desc: "Submission of the research logbook and status document 2 which provides an overview of all key tasks conducted by members during the implementation phase of the research.",
    marks: "Marks Allocation - 2%",
    date: "October 31, 2023",
    type: "doc",
  },
  {
    title: "Website Assessment",
    desc: "Submission of research website for evaluation.",
    marks: "Marks Allocation - 2%",
    date: "November 6, 2023",
    type: "doc",
  },
  {
    title: "Final Presentation and Viva",
    desc: "Final evaluation of the completed product.",
    marks: "Marks Allocation - 20%",
    date: "November 1, 2023",
    type: "viva",
  },
];
